openapi: 3.0.0
info:
  title: API Simples
  version: 1.0.0
paths:
  /itens:
    get:
      summary: Lista todos os itens
      responses:
        '200':
          description: Lista de itens
    post:
      summary: Cria um novo item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                descricao:
                  type: string
      responses:
        '201':
          description: Item criado
  /itens/{id}:
    put:
      summary: Atualiza um item
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                descricao:
                  type: string
      responses:
        '200':
          description: Item atualizado
        '404':
          description: Item não encontrado
    delete:
      summary: Deleta um item
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Item deletado
        '404':
          description: Item não encontrado