name: CI Manual

on:
  push:
    branches:
      - main
  # workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
      - name: Build
        run: echo "build"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Teste
        run: echo "test"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    # environment:
    #   name: manual-approval
    steps:
      - name: Deploy
        run: echo "deploy"
